databases:
  - name: boxd
    databaseName: boxd
    user: boxd

services:
  - type: web
    name: boxd
    env: ruby
    plan: standard 
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: boxd
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false